### ISSUE TITLE
/etc/localtime issues during build

### ISSUE THREAD

**Issue by arb1961** [apjanke/octave-tablicious#63] opened 2020-01-24 14:50 UTC
building the snapshot I get this message on /etc/localtime, see line in bold below.

copyfile /tmp/oct-SdCGRs/tablicious-0.4.0-SNAPSHOT/src/__oct_time_binsearch__.oct /tmp/oct-SdCGRs/tablicious-0.4.0-SNAPSHOT/inst/x86_64-pc-linux-gnu-api-v53
**Failed detecting system time zone: Can't determine time zone: Failed reading /etc/localtime: Invalid argument**
Falling back to ''

this is on linux,

file /etc/localtime returns this:
/etc/localtime: timezone data, version 2, 13 gmt time flags, 13 std time flags, no leap seconds, 180 transition times, 13 abbreviation chars

**Comment by apjanke** [comment] 2020-01-27 12:55
Thanks for the bug report! I'll look in to this.

**Comment by apjanke** [comment] 2020-01-27 13:21
I'm afraid I'm unable to reproduce on Ubuntu 19. For me, the package installs and time zone detection runs without the error you're getting.

```
octave:1> pkg install https://github.com/apjanke/octave-tablicious/releases/download/v0.3.0/tablicious-0.3.0.tar.gz
warning: doc_cache_create: unusable help text found in file 'calendarDuration'
warning: doc_cache_create: unusable help text found in file 'categorical'
warning: doc_cache_create: unusable help text found in file 'datetime'
warning: doc_cache_create: unusable help text found in file 'duration'
warning: doc_cache_create: unusable help text found in file 'localdate'
warning: doc_cache_create: unusable help text found in file 'missing'
warning: doc_cache_create: unusable help text found in file 'string'
warning: doc_cache_create: unusable help text found in file 'table'
octave:2> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
  tablicious  |   0.3.0 | /home/janke/octave/tablicious-0.3.0
octave:3> pkg load tablicious
octave:4> octave.chrono.internal.detect_system_timezone
ans = America/New_York
octave:5> 
```

What Linux distro are you running, and what version of Octave?

**Comment by arb1961** [comment] 2020-01-27 22:29
Hi, here some additional platform info:

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)

uname -a
Linux 2.6.32-696.3.1.el6.x86_64 #1 SMP Thu Apr 20 11:30:02 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

file /etc/localtime
/etc/localtime: timezone data, version 2, 13 gmt time flags, 13 std time flags, no leap seconds, 180 transition times, 13 abbreviation chars

**Comment by arb1961** [comment] 2020-01-27 22:39
So I pulled and built (getting version 0.3.1). The build now completes, with the /etc/localtime warning still there. A first tablicious test in octave-5.1.90, shows that the first datetime call produces the same warning, subsequent calls are silent (and give the correct local time in this case).

app-dusk01.tsn.tno.nl{~ }186: octave -q
octave:1> version
ans = 5.1.90
octave:2> pkg load tablicious
octave:3> datetime
warning: Failed detecting system time zone: Can't determine time zone: Failed reading /etc/localtime: Invalid argument
Falling back to ''
warning: called from
    detect_system_timezone at line 28 column 5
ans =
 27-Jan-2020 23:33:34
octave:4> datetime
ans =
 27-Jan-2020 23:33:39

**Comment by apjanke** [comment] 2020-01-27 22:42
Thanks! I'll spin up a RHEL VM and try to reproduce there. I should be able to get to this some time tonight.

**Comment by apjanke** [comment] 2020-01-28 02:28
I think I see the problem. The time zone detection logic assumes that if `/etc/localtime` exists, it a symlink into the main `zoneinfo` db file hierarchy. Maybe that's not the case on RHEL 6; maybe it's a hardlink or copied file there.

Could you do me a favor and tell me what `ls -l /etc/localtime` displays for you?

Still working on getting my own RHEL 6 VM built.

**Comment by apjanke** [comment] 2020-01-28 05:24
Got my RHEL 6 VM built.

Yep, looks like that's the problem: In RHEL 7 and 8, `/etc/localtime` is a symlink into `zoneinfo`. But on RHEL 6, it's a regular file.

I'll have to rearrange the Tablicious code so it's able to extract the time zone info directly from the file, instead of relying on it being a symlink. This will take a little while.

In the meantime, I've checked in a change to have the code fall fall through and use Java to detect the time zone if you have a Java-enabled Octave build. Please try re-installing Tablicious from the head of `master` (`pkg install https://github.com/apjanke/octave-tablicious/archive/master.zip`). At that point you can ignore the warning if it still happens. Or you can set your `TZ` environment variable, which Tablicious will prefer to the other detection means, and that will get rid of the warning.

**Comment by arb1961** [comment] 2020-01-28 07:13
output of ls -l
ls -l /etc/localtime
-rw-r--r-- 1 root root 2923 Mar  9  2017 /etc/localtime

after a pull tablicious now builds cleanly, and loads.

One thing I noticed is that the first datetime call takes a bit longer than subsequent calls, which maybe has to do with java related initialization.

octave:1> pkg load tablicious
octave:2> tic;datetime;toc
Elapsed time is 1.62186 seconds.
octave:3> tic;datetime;toc
Elapsed time is 0.000901937 seconds.

**Comment by apjanke** [comment] 2020-01-28 07:20
Great!

That performance hit on the first call is normal: There is Java initialization, Octave initialization (you take a hit the first time you call any function or class, since it has to parse and initialize the M-code of that function and all its dependencies that get called), and, in this case, Time Zone database initialization, which involves some I/O and parsing.

I'm going to leave this issue open until I have a real fix that knows how to read the `/etc/localtime` file directly.

Let me know if you have any other trouble.

**Comment by apjanke** [comment] 2020-01-29 23:36
Sigh. Turns out the zone info files do not store their names internally, so there's no way to tell exactly what zone it is by examining the file contents. (Even comparing the file contents to all the files in the tzdb won't work, because some time zones are aliases of each other. I suppose we could just pick one of the aliases randomly.)

I'm afraid that on Red Hat 6, you're stuck having to set your `$TZ` environment variable, unless you know of some other way of detecting the time zone on Red Hat 6.

**Closed by apjanke** 2020-01-29 23:36 UTC
Labels: bug

**Comment by mtmiller** [comment] 2020-01-29 23:44
I don't know how much you care about working around this, but IIRC Red Hat systems had a file under /etc/sysconfig that stored the name of the system time zone, assuming it was configured properly.

It's also not _that_ fatal that the system time zone can't be detected, time functions should still work for the most part without it.

**Comment by apjanke** [comment] 2020-01-29 23:47
That's right: very little of the functionality in the date/time stuff in Tablicious requires the system/default time zone; almost everything will work just fine for you.

But I do care about fixing this: obviously people out there are still using RH 6, and I want to support as many users as possible.

Thanks for the tip. I'll look in to this.

**Comment by apjanke** [comment] 2020-01-29 23:49
Hmm. I think I found it: `/etc/sysconfig/clock`. But it says this:

```
# The time zone of the system is defined by the contents of /etc/localtime.
# This file is only for evaluation by system-config-date, do not rely on its
# contents elsewhere.
ZONE="America/New_York"
```

Given that warning, I don't know if I want to use that file. I don't like using unsupported things, even if they seem like they'll work.

**Comment by mtmiller** [comment] 2020-01-29 23:52
Yeah, so the official support docs tell Red Hat 5 and 6 admins to always use the system-config-date tool to set the system clock and time zone, which reads and sets that file in addition to overwriting /etc/localtime. But nothing stops an admin from manually copying or symlinking /etc/localtime to whatever they want, and that file is out of sync. Other than that, I think there's no fallback.

**Comment by apjanke** [comment] 2020-01-30 00:00
Hmmmmmmm. Sounds like the failure case in a misconfigured system is that Tablicious's detected time zone would be inconsistent with the actual system time zone definition. I don't think I'm _currently_ doing anything in Tablicious itself where that would matter. But if a user wrote code on top of it that compared "system default time zone" dates generated by Tablicious to dates from an external source on the system, there could be inconsistencies. Hmmm.

**Comment by apjanke** [comment] 2020-01-30 00:22
Okay, tell you what: Let's leave it as is for now, but if you run in to anything where the lack of time zone detection on RHEL 6 actually causes you problems, I'll add in detection using `/etc/sysconfig/clock` or something else.
