### ISSUE TITLE
Issues installing with Octave 8.4.0

### ISSUE THREAD

**Issue by wrthissell** [apjanke/octave-tablicious#107] opened 2023-12-03 23:31 UTC
I tried and finally compiled and installed tablicious 0.3.7 tonight in Octave 8.4.0 64 bit for Windows 10.  Here is my record:

>> pkg install https://github.com/apjanke/octave-tablicious/releases/download/v0.3.7/tablicious-0.3.7.tar.gz

error: pkg: failed downloading 'https://github.com/apjanke/octave-tablicious/releases/download/v0.3.7/tablicious-0.3.7.tar.gz': Timeout was
reached
error: called from
    pkg at line 571 column 19
>> pkg install tablicious-0.3.7.tar.gz
warning: function C:\Users\thissell\AppData\Roaming\octave\api-v58\packages\tablicious-0.3.7\endsWith.m shadows a core library function
warning: called from
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: function C:\Users\thissell\AppData\Roaming\octave\api-v58\packages\tablicious-0.3.7\startsWith.m shadows a core library function
warning: called from
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: doc_cache_create: unusable help text found in file 'categorical'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: doc_cache_create: unusable help text found in file 'datetime'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: doc_cache_create: unusable help text found in file 'localdate'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: doc_cache_create: unusable help text found in file 'missing'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: doc_cache_create: unusable help text found in file 'string'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: doc_cache_create: unusable help text found in file 'table'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

>>

You will see that the automated download of the .gz file failed.  I then manually downloaded it from github and tried again.  This time the installation resulted in many warnings.  I will now try to use this package and report back with my findings.

**Comment by apjanke** [comment] 2024-01-30 05:07
I think this is all fixed on the `main` branch. A Tablicious 0.4.0 release with the fixes will be coming soon.

If you want to test this out ahead of time, you can clone the repo or download a copy of its contents from GitHub, and add its `inst/` directory to your Octave path. That should get everything except the `datetime` time zone conversions working. It's working for me under Octave 8.4.0 on macOS that way.

I couldn't reproduce the download timeout you had there. Think that may have been in intermittent network or GitHub issue, not something in Tablicious itself?

**Comment by apjanke** [comment] 2024-01-30 05:25
Closing as a duplicate of https://github.com/apjanke/octave-tablicious/issues/106; please re-open if you have any problems that aren't covered there.

**Closed by apjanke** 2024-01-30 05:25 UTC
Labels: bug
