### ISSUE TITLE
error: pkg: error running 'make' for the tablicious package.

### ISSUE THREAD

**Issue by ludokyeho** [apjanke/octave-tablicious#78] opened 2021-05-15 17:28 UTC
Hey, after a bug with Octave I had to reinstall, and when I wanted to reinstall the tablicious package, I was given this error message:

 `pkg install "https://github.com/apjanke/octave-tablicious.git"`
 error: pkg: error running 'make' for the tablicious package.
 error: called from
     configure_make at line 110 column 9
     install at line 196 column 7
     pkg at line 568 column 9
    
  `   pkg load tablicious`
 error: package tablicious is not installed
 error: called from
     load_packages at line 47 column 7
     pkg at line 588 column 7

I have no clue what's wrong? 
I downloaded Ocatve v6 and think I had v5 before? 
Could this be the problem? 
Thanks in advance!

**Comment by apjanke** [comment] 2021-05-16 01:05
> I downloaded Ocatve v6 and think I had v5 before?

Well, that's not _supposed_ to be the problem, but maybe we've introduced a v6 incompatibility in Tablicious? I haven't tested it on Octave 6 yet.

What OS are you running on?

**Comment by ludokyeho** [comment] 2021-05-16 09:55
Hey, I'm running it on windows 10 
I asked a friend to run the code who also had v6.2.0 so I think that clears the problem. 
I think it's related to a problem I had prior to this: 
My octave just stopped working out of the blue (kept crashing as soon as it oppened) and the only solution I found was to install v4. It worked but then I tried to reinstall the latest version and to do so deleted all previous versions of octave from my pc and when in installing one I had a message telling me some files couldn't be deleted. Could this cause the issue?

**Comment by apjanke** [comment] 2021-07-05 23:41
> ...when in installing one I had a message telling me some files couldn't be deleted. Could this cause the issue?

Sounds likely. I have been unable to reproduce this issue.

I'd suggest uninstalling Octave again, and then trying to manually clean up all Octave-related files from both `%PROGRAMFILES%` and your `%USERPROFILE%`, using Administrator rights.

I'm closing this as an unreproducible, machine-specific upstream issue. If you can reproduce this in other environments, please re-open this Issue.

**Closed by apjanke** 2021-07-05 23:41 UTC
Labels: bug
