### ISSUE TITLE
unusable help text in Tablicious 0.3.7

### ISSUE THREAD

**Issue by geerligs** [apjanke/octave-tablicious#104] opened 2023-01-09 08:14 UTC
I  found that using tablicious 0.3.7. some help texts are unusable.
However the functions (e.g. datetime) run perfectly.
![image](https://user-images.githubusercontent.com/6309628/211264346-e54a4700-71ed-4576-8e54-a77bf100d114.png)

![image](https://user-images.githubusercontent.com/6309628/211264222-411aedb4-d102-4d28-a1d1-588c3b9d7460.png)

**Comment by apjanke** [comment] 2023-01-14 22:23
Did those warnings pop up during the package installation? If so, you've run in to an existing known bug: https://github.com/apjanke/octave-tablicious/issues/85. And I have no idea what to do about that; suggestions welcome. Might even require changes in core Octave.

If those warnings popped up in response to you calling `datetime('2011-03-04')` or something like that, then that's a whole new thing.

**Comment by geerligs** [comment] 2023-01-17 13:13
Warnings did only pop up during installation. So it looks like #85 

Function datetime and the other ones work fine :-)

**Comment by apjanke** [comment] 2023-01-17 13:20
Cool. (And sorry.)

Closing this bug report as a duplicate of #85 . Please follow there for further updates.

**Closed by apjanke** 2023-01-17 13:20 UTC
